- id: 'Aggiornamento HA'
  alias: Aggiornamento HA
  trigger:
    - platform: state
      entity_id: updater.updater
  action:
    - service: notify.notify
      data:
        title: "Home Assistant"
        message: 'aggiornamento {{ states.updater.updater.state }} è disponibile'
