- platform: generic_thermostat
  name: Termostato
  heater: switch.attivazione_termostato
  target_sensor: sensor.temperatura_atrio
  min_temp: 15
  max_temp: 22
  ac_mode: False
  target_temp: 17
  cold_tolerance: 0.3
  hot_tolerance: 0.3
  min_cycle_duration:
    seconds: 5
  keep_alive:
    minutes: 3
  initial_operation_mode: "off"
  away_temp: 16
  precision: 0.1