api:

alexa: !include alexa.yaml

automation: !include automations.yaml

binary_sensor: !include_dir_merge_list binary_sensor

camera: !include_dir_merge_list cameras

config:

custom_updater:

discovery:

device_tracker: !include device_tracker.yaml

frontend: !include frontend.yaml

group: !include group.yaml

history:

http: !include http.yaml

homeassistant: !include home_assistant.yaml

homekit:

input_boolean: !include input/input_boolean.yaml

input_number: !include input/input_number.yaml

input_select: !include input/input_select.yaml

input_text: !include input_text.yaml

ios:

light: !include_dir_merge_list light

logbook:

map:

media_player: !include_dir_list media_player

notify: !include notify.yaml

owntracks: !include owntracks.yaml

panel_iframe: !include panel_iframe.yaml

person: !include person.yaml

python_script:

proximity: !include proximity.yaml

script: !include scripts.yaml

sensor: !include_dir_merge_list sensor

sun:

system_health:

switch: !include_dir_merge_list switch

telegram_bot: !include telegram_bot.yaml

tts:
  - platform: google

updater:

zone: !include zone.yaml
