homeassistant: !include home_assistant.yaml

system_health:

automation: !include_dir_merge_list automations

frontend:
  themes: !include themes.yaml

config:

updater:
# Optional, allows Home Assistant developers to focus on popular components.
# include_used_components: true

discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

# Text to speech
tts:
  - platform: google

api:

alexa: !include alexa.yaml

homekit:

ios:

mqtt: !include mqtt.yaml

telegram_bot: !include telegram_bot.yaml

zone: !include zone.yaml

climate: !include climate.yaml

group: !include groups.yaml

script: !include scripts.yaml

http: !include http.yaml

sensor: !include_dir_merge_list sensor

binary_sensor: !include_dir_merge_list binary_sensor

camera: !include_dir_merge_list cameras

notify: !include notify.yaml

device_tracker: !include device_tracker.yaml

owntracks: !include owntracks.yaml

proximity: !include proximity.yaml

panel_iframe: !include panel_iframe.yaml

light: !include_dir_merge_list light

switch: !include_dir_merge_list switch

input_select: !include input/input_select.yaml

input_number: !include input/input_number.yaml

media_player: !include_dir_list media_player
