########################################################################################## 
#                                                                                        #
#                                        /START                                          #
#                                                                                        # 
##########################################################################################

automation:

  - alias: 'Telegram_Bot_Start'
    hide_entity: true
    initial_state: 'on'
    trigger:
      - platform: event
        event_type: telegram_command
        event_data:
          command: /start
    action:
      - service: notify.telegram
        data_template:
          title: Benvenuto
          message: '*PANNELLO DI CONTROLLO*'
          data:
            inline_keyboard:
              - '{{ "\U0001F6A8" }} Sicurezza:/sicurezza,{{ "\U0001F4A1" }} Luci:/luci' 
              - '{{ "\U0001F4BB" }} Sistema:/sistema,{{ "\U0001F6AA" }} Sensori:/sensori'
              - '{{ "\U0001F4C4" }} Sommario:/Sommario,{{ "\U00002600" }} Meteo:/meteo'

########################################################################################## 
#                                                                                        #
#                                        /STOP                                           #
#                                                                                        # 
##########################################################################################
                
  - alias: 'Telegram_Bot_Stop'
    hide_entity: true
    trigger:
      - platform: event
        event_type: telegram_callback
        event_data:
          data: /stop
    action:
      - service: notify.telegram
        data_template:
          message: '*PANNELLO DI CONTROLLO*'
          data:
            inline_keyboard:
              - '{{ "\U0001F6A8" }} Sicurezza:/sicurezza,{{ "\U0001F4A1" }} Luci:/luci' 
              - '{{ "\U0001F4BB" }} Sistema:/sistema,{{ "\U0001F6AA" }} Sensori:/sensori'
              - '{{ "\U0001F4C4" }} Sommario:/Sommario,{{ "\U00002600" }} Tempo:/meteo'
