automation:

########################################################################################## 
#                                                                                        #
#                                    INFO SISTEMA                                        #
#                                                                                        # 
##########################################################################################

  - alias: 'Info Sistema'
    hide_entity: true
    trigger:
    - platform: event
      event_type: telegram_callback
      event_data:
        data: /sistema
    action:
    - service: notify.telegram
      data_template:

        message: >- 
        
          {{ "\U0001F4BB" }} *SISTEMA*:
        
          *Uso CPU*:   {{ states.sensor.processor_use.state }} %
        
          *Tempo attivo*:   {{ states.sensor.uptime.state }}
        
          *Ultimo Riavvio*:   {{ states.sensor.last_boot.state }}
        
          *Temp CPU*:   {{ states.sensor.cpu_temp.state }}
        
          *Memoria Libera*:   {{ states.sensor.memory_free.state }}
          
          *Memoria Usata*: {{ states.sensor.memory_use.state }}
        
          
          
        data:
          inline_keyboard:
            - '{{ "\u21a9\ufe0f" }} Menú Principale:/stop'
