automation:

########################################################################################## 
#                                                                                        #
#                                        SENSOR                                          #
#                                                                                        # 
##########################################################################################

  - alias: 'info sensori'
    hide_entity: true
    trigger:
    - platform: event
      event_type: telegram_callback
      event_data:
        data: /sensori
    action:
      - service: telegram_bot.answer_callback_query
        data_template:
          callback_query_id: '{{ trigger.event.data.id }}'
          message: Sensori
      - service: notify.telegram
        data_template:

          message: >- 
        
            {{ "\U0001F6AA" }} *SENSORI*:
            -----------------------------------
            
            *Stato Porte Finestre*:   
        
            *Porta Ingresso* {{ state_attr('binary_sensor.0x00158d00024b3317_contact', 'contact') }}
        
            *Porta Cameretta* {{ state_attr('binary_sensor.0x00158d0001e773aa_contact', 'contact') }}
        
            *Finestra Terrazzo* {{ state_attr('binary_sensor.0x00158d0001e74ab4_contact', 'contact') }}
        
        
        
            {{ "\U0001F321" }} *TEMPERATURE*:
            -----------------------------------    
        
            *Temperatura Sala*:   {{ state_attr('sensor.0x00158d0002227ec4_temperature', 'temperature') }} ºC
          
            *Temperatura Cucina*:   {{ state_attr('sensor.0x00158d00022cac7b_temperature', 'temperature') }} ºC
        
            *Temperatura Salagiochi*:   {{ state_attr('sensor.0x00158d0001fa5436_temperature', 'temperature') }} ºC
        
            *Temperatura Matrimoniale*:   {{ state_attr('sensor.0x00158d0001f46f6f_temperature', 'temperature') }} ºC
        
            *Temperatura Cameretta*:   {{ state_attr('sensor.0x00158d0001f4713e_temperature', 'temperature') }} ºC
        
            *Temperatura Studio*:   {{ state_attr('sensor.0x00158d000223f3f4_temperature', 'temperature') }} ºC
        
            *Temperatura Bagno D.*:   {{ state_attr('sensor.0x00158d0002227f42_temperature', 'temperature') }} ºC
        
            *Temperatura Bagno V.*:   {{ state_attr('sensor.0x00158d0001fa3d12_temperature', 'temperature') }} ºC
        
          data:
            inline_keyboard:
              - '{{ "\u21a9\ufe0f" }} Menú Principale:/stop'
