automation:
########################################################################
### TELEGRAM HASSIO UPDATE
########################################################################

  - alias: 'Telegram_Bot_Service'
    initial_state: true
    trigger:
      - platform: event
        event_type: telegram_callback
        event_data:
          data: /servizi
    action:
      - service: telegram_bot.answer_callback_query
        data_template:
          callback_query_id: '{{ trigger.event.data.id }}'
          message: "*MENU' SERVIZI*"
          show_alert: false
      - service: telegram_bot.send_message
        data_template:
          target: '{{ trigger.event.data.user_id }}'
          message: "*MENU' SERVIZI*"
          inline_keyboard:
            - '{{ "\U0001F4A1" }} Aggiornare:/update, {{ "\U0001F4A1" }} Riavviare:/reboot'
            - '{{ "\U0001F4A1" }} Spegnere:/shutdown'
            - '{{ "\u21a9\ufe0f" }} Menú Principale:/stop'

  - alias: Servizio Aggiornamento
    initial_state: true
    trigger:
      - platform: event
        event_type: telegram_callback
        event_data:
          data: /update
    action:
      - service: telegram_bot.send_message
        data_template:
          message: Home Assistant verrà aggiornato alla {{ states('sensor.latest_version') }}
      - delay: '00:00:02'
      - service: hassio.addon_stdin
        data:
          addon: a0d7b954_ssh
          input: '/usr/bin/ha core update'
      - delay: '00:00:02'
      - service: telegram_bot.send_message
        data:
          message: Aggiornamento in corso

  - alias: Servizio Riavvio
    initial_state: true
    trigger:
      - platform: event
        event_type: telegram_callback
        event_data: 
          data: /reboot
    action:
      - data:
          message: Riavvio
        service: telegram_bot.send_message
      - delay: '00:00:01'
      - service: homeassistant.restart 

  - alias: Servizio Spegnimento
    initial_state: true
    trigger:
      - platform: event
        event_type: telegram_callback
        event_data: 
          data: /shutdown
    action:
      - data:
          message: Spegnimento
        service: telegram_bot.send_message
      - delay: '00:00:01'
      - service: homeassistant.stop
