automation:
  
  - alias: 'Avvio Samba Addon'
    initial_state: true
    trigger:
      - event: start
        platform: homeassistant
    condition:
      - condition: state
        entity_id: sensor.samba
        state: 'stopped'
    action:
      - service: hassio.addon_start
        data:
          addon: core_samba

  - alias: 'Avvio Mariadb Addon'
    initial_state: true
    trigger:
      - event: start
        platform: homeassistant
    condition:
      - condition: state
        entity_id: sensor.mariadb
        state: 'stopped'
    action:
      - service: hassio.addon_start
        data:
          addon: core_mariadb

####################################
#  ╔═╗╔╦╗╔╦╗╔═╗╔╗╔  ╔═╗╔═╗╦═╗╔╦╗╦  #
#  ╠═╣ ║║ ║║║ ║║║║  ╠╣ ║╣ ╠╦╝║║║║  #
#  ╩ ╩═╩╝═╩╝╚═╝╝╚╝  ╚  ╚═╝╩╚═╩ ╩╩  #
####################################

  - alias: Addon Fermi
    initial_state: true  
    trigger:
      platform: state
      entity_id:
        - sensor.web_ssh
        - sensor.mosquitto
        - sensor.samba
        - sensor.vscode
        - sensor.mariadb
      from: started
      to: stopped
    action:
      - service: notify.telegram
        data_template:
          title: "Addon Fermi"
          message: "{{ trigger.to_state.entity_id }} addon è fermo"

##########################################################
#  ╔═╗╔═╗╔═╗╦╔═╗╦═╗╔╗╔╔═╗╔╦╗╔═╗╔╗╔╔╦╗╦  ╔═╗╔╦╗╔╦╗╔═╗╔╗╔  #
#  ╠═╣║ ╦║ ╦║║ ║╠╦╝║║║╠═╣║║║║╣ ║║║ ║ ║  ╠═╣ ║║ ║║║ ║║║║  #
#  ╩ ╩╚═╝╚═╝╩╚═╝╩╚═╝╚╝╩ ╩╩ ╩╚═╝╝╚╝ ╩ ╩  ╩ ╩═╩╝═╩╝╚═╝╝╚╝  #
##########################################################

  - alias: Aggiornamento Addon
    initial_state: true
    trigger:
      platform: template
      value_template: "{{ states('sensor.supervisor_updates') != '0'}}"
    mode: parallel
    max: 10  
    condition:
      - condition: template
        value_template: "{{ trigger.from_state.state != trigger.to_state.state }}"
    action:
      service: notify.telegram
      data_template:
        title: "Aggiornamento Add-On Disponibile"
        message: >-
          ------
          {% for addon in states.sensor.supervisor_updates.attributes.addons %}
            {{addon.name }}: {{ addon.installed }} -> {{ addon.version }}
          {% endfor %} 

#######################################################
#  ╔═╗╔═╗╔═╗╦╔═╗╦═╗╔╗╔╔═╗╔╦╗╔═╗╔╗╔╔╦╗╦  ╦ ╦╔═╗╔═╗╔═╗  #
#  ╠═╣║ ╦║ ╦║║ ║╠╦╝║║║╠═╣║║║║╣ ║║║ ║ ║  ╠═╣╠═╣║  ╚═╗  #
#  ╩ ╩╚═╝╚═╝╩╚═╝╩╚═╝╚╝╩ ╩╩ ╩╚═╝╝╚╝ ╩ ╩  ╩ ╩╩ ╩╚═╝╚═╝  #
#######################################################

  - alias: Aggiornamento HACS
    initial_state: true
    trigger:
      platform: template
      value_template: "{{ states('sensor.hacs') != '0'}}"
    mode: parallel
    max: 10
    condition:
      - condition: template
        value_template: "{{ trigger.from_state.state != trigger.to_state.state }}"
    action:
      service: notify.telegram
      data_template:
        title: "Aggiornamento HACS Disponibile"
        message: >-
          ------
          {% for hacs in states.sensor.hacs.attributes.repositories %}
            {{hacs.display_name }}: {{ hacs.installed_version }} -> {{ hacs.available_version }}
          {% endfor %}

