sensor:

  - platform: moon

  - platform: template
    sensors:

      moon_state:
        friendly_name: "Fasi Lunari"
        entity_id: sensor.moon
        value_template: >-
          {{ {
          'new_moon' : 'Nuova',
          'waxing_crescent' : 'Crescente',
          'first_quarter' : 'Primo Quarto',
          'waxing_gibbous' : 'Gibbosa Crescente',
          'full_moon' : 'Piena',
          'waning_gibbous' : 'Gibbosa Calante',
          'last_quarter' : 'Ultimo Quarto',
          'waning_crescent' : 'Calante'
          } [states('sensor.moon')] }}
        icon_template: >-
          {{ {
          'new_moon' : 'mdi:moon-new',
          'waxing_crescent' : 'mdi:moon-waxing-crescent',
          'first_quarter' : 'mdi:moon-first-quarter',
          'waxing_gibbous' : 'mdi:moon-waxing-gibbous',
          'full_moon' : 'mdi:moon-full',
          'waning_gibbous' : 'mdi:moon-waning-gibbous',
          'last_quarter' : 'mdi:moon-last-quarter',
          'waning_crescent' : 'mdi:moon-waning-crescent'
          } [states('sensor.moon')] }}
