################################################################################
#                                                                              #
################################## SPEEDTEST ###################################
#                                                                              #
################################################################################

speedtestdotnet:

  scan_interval:
    minutes: 30
  monitored_conditions:
    - ping
    - download
    - upload

################################################################################
#                                                                              #
################################# EXTERNAL IP ##################################
#                                                                              #
################################################################################

sensor:
  
  - platform: dnsip  
