sensor:

  - platform: template
    sensors:
          
      spazzatura:
        friendly_name: "Ritiro"
        entity_id: sensor.weekday
        value_template: >-
          {% set date = states('sensor.date')%}
          {% set inverno = ["Umido", "Non riciclabile", "Carta", "Vetro", "Umido", "Nessun ritiro", "Plastica"] %} 
          {% set estate =  ["Umido", "Non riciclabile", "Carta e Umido", "Vetro", "Umido", "Nessun ritiro", "Plastica"] %} 
          {% set ritiro_inverno = inverno[now().weekday()] %}
          {% set ritiro_estate = estate[now().weekday()] %}
          {% if now().month in [6,7,8,9,10]  %}
            {{ ritiro_estate }}
          {% else %}
            {{ ritiro_inverno }}
          {% endif %}
        icon_template: >
          mdi:{{['apple','delete-empty','newspaper','glass-cocktail','apple','circle-off-outline','food-fork-drink' ]
              [now().weekday()]}}
