sensor:

  - platform: time_date
    display_options:
      - time
      - date

  - platform: template
    sensors:
          
      odd_even:
        friendly_name: 'Giorno'
        value_template: >
          {% if states('sensor.date') and now().day % 2 == 1 %}
            Dispari
          {% else %}
            Pari
          {% endif %}

      weekday:
        friendly_name: "Giorno della Settimana"
        value_template: >
          {{ states('sensor.date') and ['Lunedì','Martedì', 'Mercoledì', 'Giovedì', 'Venerdì', 'Sabato', 'Domenica'][now().weekday()]}}
        icon_template: >
          mdi:{{['emoticon-dead-outline', 'emoticon-angry-outline', 'emoticon-sad-outline','emoticon-neutral-outline','emoticon-cool-outline','emoticon-excited-outline','emoticon-happy-outline'][now().strftime('%A')] }}

      month:
        friendly_name: Mese
        value_template: >
           {{ states('sensor.date') and ['Dicembre','Gennaio','Febbraio','Marzo','Aprile','Maggio','Giugno','Luglio','Agosto','Settembre','Ottobre','Novembre'][now().month] }}
        icon_template: mdi:calendar-month

      fine_del_mese:
        friendly_name: "Fine Del Mese"
        value_template: >
          {% set date = states('sensor.date') %}
          {% if now().month in [1,3,5,7,8,10,12] %}
            {{ 31 - now().day }}
          {% elif now().month in [4,6,9,11] %}
            {{ 30 - now().day }}
          {% elif now().month == 2 and ((now().year-2000) % 4 > 0) %}
            {{ 28 - now().day }}
          {% elif now().month == 2 and ((now().year-2000) % 4 == 0) %}
            {{ 29 - now().day }}
          {% endif %}
