sensor:

  - platform: time_date
    display_options:
      - time
      - date


          # {{ now().strftime("%d-%m-%Y") }}

  - platform: template
    sensors:
          
      odd_even:
        friendly_name: 'Giorno'
        entity_id: sensor.date
        value_template: >
          {% if (now().strftime("%-d") | int % 2) == 0 %}
            Pari
          {% else %}
            Dispari
          {% endif %}

      weekday:
        friendly_name: Settimana
        entity_id: sensor.date
        icon_template: mdi:calendar-range
        value_template: >
          {% set days = ["Lunedì", "Martedì", "Mercoledì", "Giovedì", "Venerdì", "Sabato", "Domenica"] %}
          {% set weekday = days[now().weekday()] %}
            {{ weekday }}

      month:
        friendly_name: Mese
        entity_id: sensor.date
        icon_template: mdi:calendar-range
        value_template: >
          {% set mese = ["Dicembre","Gennaio","Febbraio","Marzo","Aprile","Maggio","Giugno","Luglio","Agosto","Settembre","Ottobre","Novembre"] %}
          {% set month = mese[now().month] %}
            {{ month }}

      fine_del_mese:
        friendly_name: "Fine Del Mese"
        entity_id: sensor.date
        value_template: >
          {% if now().month in [1,3,5,7,8,10,12] %}
            {{ 31 - now().day }}
          {% elif now().month in [4,6,9,11] %}
            {{ 30 - now().day }}
          {% elif now().month == 2 and ((now().year-2000) % 4 > 0) %}
            {{ 28 - now().day }}
          {% elif now().month == 2 and ((now().year-2000) % 4 == 0) %}
            {{ 29 - now().day }}
          {% endif %}
