sensor:
  - platform: mqtt
    name: "Soglia kWh Impostato"
    state_topic: "zigbee2mqtt/#aggiungere_nome_dispositivo#"
    availability_topic: "zigbee2mqtt/bridge/state"
    unit_of_measurement: "kWh"
    value_template: "{{ value_json.power_alarm_wh_threshold / 1000 }}"
    icon: "mdi:flash"
