- platform: mqtt 
  name: "Attivazione Termostato"
  state_topic: "stat/termostato/POWER"
  command_topic: "cmnd/termostato/POWER"
  availability_topic: "tele/termostato/LWT"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: false