automation:

  - alias: 'Pihole Auto Updater Notification'
    trigger:
      - platform: state
        entity_id: 'sensor.pihole_check'
        to: 'Update'
    condition:
      - condition: state
        entity_id: input_boolean.pihole_auto_updater
        state: 'on'
    action:
      - service: script.pihole_updater
      - service: notify.telegram
        data_template:
          message: "Pihole è Stato Aggiornato Automaticamente"

  - alias: 'Pihole Manual Updater Notification'
    trigger:
      - platform: state
        entity_id: 'sensor.pihole_check'
        to: 'Update'
    condition:
      - condition: state
        entity_id: input_boolean.pihole_auto_updater
        state: 'off'
    action:
      - service: notify.telegram
        data_template:
          message: "Pihole è Da Aggiornare Manualmente"
