sensor:
    
#  - platform: command_line
#    name: "PiHole Status CML"
#    command: !secret pihole_status_curl
#    command: "curl -X GET 'http://IP-PIHOLE/admin/api.php?status'"
#    value_template: '{{ value_json.status }}'
    
#  - platform: command_line
#    name: "PiHole Version CML"
#    command: !secret pihole_version_curl
#    command: "curl -X GET 'http://IP-PIHOLE/admin/api.php?version'"
#    value_template: >-
#      {{ value_json.core_current }}
#      {{ value_json.core_latest }}
#      {{ value_json.web_current }}
#      {{ value_json.web_latest }}
#      {{ value_json.FTL_current }}
#      {{ value_json.FTL_latest }}
 
  - platform: rest
    name: "PiHole Status"
    resource: !secret pihole_status
    value_template: '{{ value_json.status }}'

  - platform: rest
    name: "PiHole Version"
    resource: !secret pihole_version
    value_template: '{{ value_json.versions }}'
    json_attributes:
      - core_current
      - core_latest
      - web_current
      - web_latest
      - FTL_current
      - FTL_latest

  - platform: template
    sensors:
    
      pihole_check:
        friendly_name: "PiHole Check"
        value_template: >-
          {% if (is_state_attr("sensor.pihole_version", "core_update", true) or
            is_state_attr("sensor.pihole_version", "web_update", true) or
            is_state_attr("sensor.pihole_version", "FTL_update", true)) %}
            Update
          {% else %} 
            Latest Update
          {% endif %}
        icon_template: >-
          {{ {
          'Latest Update' : 'mdi:checkbox-marked',
          'Update' : 'mdi:cloud-download'
          } [ states('sensor.pihole_check')] }}
