- platform: template
  sensors:
    people_home:
      value_template: >-
        {{ is_state('device_tracker.iphone_6s', 'home')
           or is_state('device_tracker.susan', 'home')
           or is_state('binary_sensor.office_124', 'on')
           or is_state('binary_sensor.hallway_134', 'on')
           or is_state('binary_sensor.living_room_139', 'on')
           or is_state('binary_sensor.porch_ms6_1_129', 'on')
           or is_state('binary_sensor.family_room_144', 'on') }}
    sun_up:
      friendly_name: "Sun is up"
      value_template: >-
        {{ states.sun.sun.attributes.elevation|float > 0 }}