- platform: mqtt
  name: "Temperatura Atrio"
  state_topic: "tele/termostato/SENSOR"
  value_template: "{{ value_json['SI7021'].Temperature }}"
  unit_of_measurement: "°C"
  availability_topic: "tele/termostato/LWT"
  payload_available: "Online"
  payload_not_available: "Offline"
- platform: mqtt
  name: "Umidità Atrio"
  state_topic: "tele/termostato/SENSOR"
  value_template: "{{ value_json['SI7021'].Humidity }}"
  unit_of_measurement: "%"
  availability_topic: "tele/termostato/LWT"
  payload_available: "Online"
  payload_not_available: "Offline"
- platform: mqtt
  name: "Termostato"
  state_topic: "stat/termostato/STATUS5"
  value_template: "IP:{{ value_json.StatusNET.IPAddress }}, MAC:{{ value_json.StatusNET.Mac }}"