automation:
###########################################################
#                  STOP BACKUP    PIENA                   #
###########################################################
  - alias: 'Stop Backup'
    trigger:
      - platform: numeric_state
        above: '85'
        below: '90'
        entity_id: sensor.disk_use_percent
    action:
      - service: notify.telegram
        data:
          message: Spazio libero in esaurimento!
      - service: automation.turn_off
        data:
          entity_id: automation.backup_full_automatico, automation.backup_partial_automatico
      - service: notify.telegram
        data:
          message: Backup Automatico disattivato
