automation:

################################################################################
#                                                                              #
################################## AVVIO HA  ###################################
#                                                                              #
################################################################################

  - alias: 'Avvio HA'
    initial_state: true
    trigger:
      - platform: homeassistant 
        event: start
    action:
      - service: notify.telegram_giancarlo
        data_template:
          message: >
            {{ [  
            "Home Assistant {{ states('sensor.current_version') }} è operativo, nessun problema",
            "Oggi è un nuovo giorno, Home Assistant {{ states('sensor.current_version') }}  è operativo.... fortunatamente", 
            "Cosa vuoi fare oggi? ah! Home Assistant {{ states('sensor.current_version') }} è operativo"
            ] | random }}

################################################################################
#                                                                              #
################################## RIAVVIO HA ##################################
#                                                                              #
################################################################################

  - alias: 'Home Assistant'
    initial_state: true
    trigger:
      - platform: homeassistant
        event: shutdown
    action:
      - service: notify.telegram_giancarlo
        data:
          message: >
            Home Assistant, il {{ now().strftime("%d-%m-%Y") }}, dalle ore {{ states('sensor.time') }}
            è momentaneamente sospeso fino al prossimo avviso.

################################################################################
#                                                                              #
################################# RIAVVIO HA ###################################
#                                                                              #
################################################################################

  - alias: 'Riavvio HA'
#    initial_state: true
    trigger:
      - platform: time
        at: 06:30:00
    condition:
      - condition: time
        weekday:
          - mon
          - tue
          - wed
          - thu
          - fri
          - sat
          - sun
    action:
      - service: homeassistant.restart
      
################################################################################
#                                                                              #
########################### NOTIFICA LOGIN ERRATI HA ###########################
#                                                                              #
################################################################################
      
  - alias: 'Notifica Login Fallito'
    initial_state: true
    trigger:
      - platform: state
        entity_id: persistent_notification.http_login
    condition:
      - condition: template
        value_template: "{{ trigger.to_state.state != 'None' }}"
    action:
      - service: notify.telegram_giancarlo
        data_template:
          title: "Tentativo Accesso"
          message: "url: https://whatismyipaddress.com/ip/{{ states.persistent_notification.http_login.attributes.message.split ('from ') [1] }}"
      - service: persistent_notification.dismiss
        data:
          notification_id: "http_login"

################################################################################
#                                                                              #
################################### CAMBIO IP ##################################
#                                                                              #
################################################################################

  - alias: 'external ip changes'
    initial_state: true
    trigger:
      - platform: state 
        entity_id: sensor.dnsip
    action:
      - service: notify.telegram_giancarlo
        data_template:
          message: "Il tuo nuovo ip è {{ states('sensor.myip') }}"

################################################################################
#                                                                              #
################################ NOTIFICA UPDATE ###############################
#                                                                              #
################################################################################

  - alias: "Notifica Update"
    trigger:
      - platform: state
        entity_id: binary_sensor.updater
        from: 'off'
        to: 'on'
    action:
      - service: notify.telegram_giancarlo
        data_template:
          message: >
            Home Assistant {{ state_attr('binary_sensor.updater', 'newest_version') }} è disponibile. 
            La tua versione attuale è {{ states('sensor.current_version') }}

################################################################################
#                                                                              #
################################# CAMBIO TEMA ##################################
#                                                                              #
################################################################################

  - alias: 'Tema Diurno'
    trigger:
      - platform: homeassistant
        event: start
      - platform: state
        entity_id: binary_sensor.day_or_night
        to: 'on'
    condition:
      - condition: state
        entity_id: binary_sensor.day_or_night
        state:  'on'
    action:
      - service: frontend.set_theme
        data:
          name: 'default'
          
  - alias: 'Tema Notturno'
    trigger:
      - platform: homeassistant
        event: start
      - platform: state
        entity_id: binary_sensor.day_or_night
        to: 'off'
    condition:
      - condition: state
        entity_id: binary_sensor.day_or_night
        state:  'off'
    action:
      - service: frontend.set_theme
        data:
          name: 'ios-dark-mode'
