################################################################################
#                                                                              #
#################################  BACKUP FULL #################################
#                                                                              #
################################################################################
automation:

  - alias: 'Backup Full Automatico'
    trigger:
      - platform: time 
        at: '10:00:00'
    condition:
      - condition: time
        weekday:
          - mon
    action:
      - service: hassio.snapshot_full
        data_template:
          name: Automated Full Backup {{ now().strftime('%Y-%m-%d') }}
          
################################################################################
#                              BACKUP FULL DROPBOX                             #
#                          scaricare ed attivare in addon                      #
#                  https://github.com/danielwelch/hassio-dropbox-sync          #
################################################################################

  - alias: 'Backup Full Dropbox'
    trigger:
      - platform: time
        at: '23:50:00'
    condition:
      - condition: time
        weekday:
          - mon
    action:
      - service: hassio.addon_stdin
        data:
          addon: 7be23ff5_dropbox_sync
          input:
            command: upload

################################################################################
#                                                                              #
############################# BACKUP PARZIALE ##################################
#                                                                              #
################################################################################

  - alias: 'Backup Partial Automatico'
    trigger:
      - platform: time
        at: '2:00:00'
    condition:
      - condition: time
        weekday:
          - mon
          - thu
          - sat
    action:
      - service: hassio.snapshot_partial
        data_template:
          name: Automated Backup {{ now().strftime('%Y-%m-%d') }}
          
################################################################################
#            in folders selezionate le cartelle che vi interessano,            #                                                                              #
#                  homeassistant è la vostra cartella /config                  #
################################################################################
          folders:
            - homeassistant
            
################################################################################
#                      in addons inserire id - nome addon,                     #
#                          ad esempio a0d7b954_nodered,                        #
#           l'id cambia se hass.io addon o la comunity o se esterno            #
################################################################################

          addons: 
            - a0d7b954_nodered

################################################################################
#                            BACKUP PARZIALE DROPBOX                           #
#                        scaricare ed attivare in addon                        #
#              https://github.com/danielwelch/hassio-dropbox-sync              #
################################################################################       

  - alias: 'Backup Partial Dropbox'
    trigger:
      - platform: time
        at: '2:50:00'
    condition:
      - condition: time
        weekday:
          - mon
          - thu
          - sat
    action:
      - service: hassio.addon_stdin
        data:
          addon: 7be23ff5_dropbox_sync
          input:
            command: upload
            
################################################################################
#                                                                              #
################################# STOP BACKUP ##################################
#                                                                              #
################################################################################ 

  - alias: 'Stop Backup'
    trigger:
      - platform: numeric_state
        above: '85'
        below: '90'
        entity_id: sensor.disk_use_percent
    action:
      - service: notify.telegram
        data:
          message: Spazio libero in esaurimento!
      - service: automation.turn_off
        data:
          entity_id: automation.backup_full_automatico, automation.backup_partial_automatico
      - service: notify.telegram
        data:
          message: Backup Automatico disattivato
