automation:

###############################################################
#  ╔╗╔╔═╗╔╦╗╦╔═╗╦╔═╗╔═╗  ╔═╗╔═╗╔╗╔╔═╗╦ ╦╔╦╗╔═╗  ╔╦╗╔═╗╔═╗╔═╗  #
#  ║║║║ ║ ║ ║╠╣ ║║  ╠═╣  ║  ║ ║║║║╚═╗║ ║║║║║ ║  ║║║║╣ ╚═╗║╣   #
#  ╝╚╝╚═╝ ╩ ╩╚  ╩╚═╝╩ ╩  ╚═╝╚═╝╝╚╝╚═╝╚═╝╩ ╩╚═╝  ╩ ╩╚═╝╚═╝╚═╝  #
###############################################################

  - alias: Costi Consumi Mese Precedente
    trigger:
      platform: time
      at: '23:59:55'
    condition:
      - condition: template
        value_template: "{{ states.sensor.fine_del_mese.state == '0' }}"
    action:
      - service: notify.telegram
        data_template:
          message: >-
            Report Consumi Mensili


            Consumo Mese: {{ (states('sensor.fascia_consumo_mensile_mono_oraria') | float)| round(2) }} kWh
            
            
            Consumo Mese precedente: {{ (states('input_number.consumo_mese_precedente') | float)| round(2) }} kWh
            
            
            Costo Mese: {{ (states('sensor.costo_mensile') | float)| round(2) }} €
            
            
            Costo Mese Precedente: {{ (states('input_number.costo_mese_precedente') | float)| round(2) }} €
      - service: input_number.set_value
        data_template:
          entity_id: input_number.consumo_mese_precedente
          value: >-
            {{ (states.sensor.fascia_consumo_mensile_mono_oraria.state | float)| round(2) }}
      - service: input_number.set_value
        data_template:          
          entity_id: input_number.costo_mese_precedente
          value: >-
            {{ (states('sensor.costo_mensile') | float)| round(2) }}'

###############################################################
#  ╔╗╔╔═╗╔╦╗╦╔═╗╦╔═╗╔═╗  ╔═╗╔═╗╔╗╔╔═╗╦ ╦╔╦╗╔═╗  ╔═╗╔╗╔╔╗╔╔═╗  #
#  ║║║║ ║ ║ ║╠╣ ║║  ╠═╣  ║  ║ ║║║║╚═╗║ ║║║║║ ║  ╠═╣║║║║║║║ ║  #
#  ╝╚╝╚═╝ ╩ ╩╚  ╩╚═╝╩ ╩  ╚═╝╚═╝╝╚╝╚═╝╚═╝╩ ╩╚═╝  ╩ ╩╝╚╝╝╚╝╚═╝  #
###############################################################

  - alias: Costi Consumi Anno Precedente
    trigger:
      platform: time
      at: '23:59:59'
    condition:
      - condition: template
        value_template: '{{ now().strftime("%m") == "12" }}'
      - condition: template
        value_template: "{{ states.sensor.fine_del_mese.state == '0' }}"
    action:
    - service: notify.telegram
      data:
        message: >
          Report Consumi Annuali
          
          
          Consumo Anno: {{ (states('sensor.fascia_consumo_annuale_mono_oraria') | float)| round(2) }} kWh
          
          
          Consumo Anno Precedente: {{(states('input_number.consumo_anno_precedente') | float)| round(2) }} kWh
          
          
          Costo Anno: {{ (states('sensor.costo_annuale') | float)| round(2) }} € 
          
          
          Costo Anno Precedente: {{(states('input_number.costo_anno_precedente') | float)| round(2) }} €      
    - service: input_number.set_value
      data_template:
        entity_id: input_number.consumo_anno_precedente
        value: >- 
          {{ (states('sensor.fascia_consumo_annuale_mono_oraria')| float)| round(2) }}
    - service: input_number.set_value
      data_template:
        entity_id: input_number.costo_anno_precedente
        value: >-
          {{ (states('sensor.costo_annuale')| float)| round(2) }}

