sensor:

  - platform: integration
    source: sensor.consumo_giornaliero_w
    name: consumo giornaliero
    unit_prefix: k
    round: 2

  - platform: template
    sensors:

      consumo_giornaliero_w:
        friendly_name: 'Consumo Giornaliero W'
        icon_template: mdi:counter
        value_template: "{{(states.sensor.shelly1pm_meters_power_ba0ced.state | float) | round(2) }}"
        unit_of_measurement: 'W'

      costo_mensile:
        friendly_name_template: 'Costo Mensile'
        icon_template: mdi:currency-eur
        value_template: "{{((states.sensor.fascia_consumo_mensile_mono_oraria.state | float) * (states.input_number.prezzo_energia.state| float)) | round(2) }}"
        unit_of_measurement: '€'

      costo_annuale:
        friendly_name_template: 'Costo Annuale'
        icon_template: mdi:currency-eur
        value_template: "{{((states.sensor.fascia_consumo_annuale_mono_oraria.state | float) * (states.input_number.prezzo_energia.state| float)) | round(2) }}"
        unit_of_measurement: '€'
