sensor:

##############################################################
#  ╔═╗╦╔╦╗╦ ╦╦ ╦╔╗   ╦ ╦╔═╗╔╦╗╔═╗  ╔═╗╔═╗╔═╗╦╔═╗╔╦╗╔═╗╔╗╔╔╦╗ #
#  ║ ╦║ ║ ╠═╣║ ║╠╩╗  ╠═╣║ ║║║║║╣   ╠═╣╚═╗╚═╗║╚═╗ ║ ╠═╣║║║ ║  #
#  ╚═╝╩ ╩ ╩ ╩╚═╝╚═╝  ╩ ╩╚═╝╩ ╩╚═╝  ╩ ╩╚═╝╚═╝╩╚═╝ ╩ ╩ ╩╝╚╝ ╩  #
##############################################################

  - platform: rest
    name: HA Fix
    resource: 'https://api.github.com/repos/home-assistant/home-assistant/releases/latest'
    username: !secret github_user
    password: !secret github_token
    authentication: basic
    value_template: '{{ value_json.tag_name}}'
    json_attributes:
      - body
      - author
    headers:
      Accept: application/vnd.github.v3+json
      Content-Type: application/json
      User-Agent: Home Assistant REST sensor

##################################################################
#  ╦  ╦╔═╗╦═╗╔═╗╦╔═╗╔╗╔  ╦ ╦╔═╗╔╦╗╔═╗  ╔═╗╔═╗╔═╗╦╔═╗╔╦╗╔═╗╔╗╔╔╦╗ #
#  ╚╗╔╝║╣ ╠╦╝╚═╗║║ ║║║║  ╠═╣║ ║║║║║╣   ╠═╣╚═╗╚═╗║╚═╗ ║ ╠═╣║║║ ║  #
#   ╚╝ ╚═╝╩╚═╚═╝╩╚═╝╝╚╝  ╩ ╩╚═╝╩ ╩╚═╝  ╩ ╩╚═╝╚═╝╩╚═╝ ╩ ╩ ╩╝╚╝ ╩  #
##################################################################

  - platform: version
    name: Current Version
    source: local

  - platform: version
    name: Latest Version
    image: qemux86-64
    source: hassio
 
  - platform: command_line
    name: HA Start
    command: grep -m1 'Home Assistant initialized' home-assistant.log | awk '{ print $6, $7, $8, $9, $10 }'

################################################################################
#                                                                              #
################################ TEMPO AVVIO HA ################################
#                                                                              #
################################################################################

  - platform: uptime
    name: Tempo Attivo
    
  - platform: template
    sensors:
      ha_last_boot:
        friendly_name_template: "Ultimo Riavvio HA"
        value_template: >
          {% set up_time = as_timestamp(now()) - as_timestamp(states('sensor.tempo_attivo')) %}
          {% if up_time == 0 %}
            0 minuti
          {% else %}
            {% macro phrase(value, name) %}
            {%- set value = value | int %}
              {{- '{} {}'.format(value, name) if value | int > 0 else '' }}
            {%- endmacro %}
            {% set minutes = (up_time // 60) %}
            {% set hours = (minutes // 60) %}
            {% set days = (hours // 24) %}
            {% set weeks = (days // 7) %}
            {% set minutes = (minutes % 60) %}
            {% set hours = (hours % 24) %}
            {% set days = (days % 7) %}
              {{[phrase(weeks, 'settimane' if weeks > 1 else 'settimana'), phrase(days, 'giorni' if days > 1 else 'giorno'), phrase(hours, 'ore' if hours > 1 else 'ora'), phrase(minutes, 'minuti' if minutes > 1 else 'minuto')] | select('!=','') | list | join(', ') }}
          {% endif %}
