sensor:

  - platform: rest
    name: HA breaking
    resource: 'https://api.github.com/repos/home-assistant/home-assistant/releases/latest'
    username: !secret github_user
    password: !secret github_token
    authentication: basic
    value_template: '{{ value_json.tag_name}}'
    json_attributes:
      - body
      - author
    headers:
      Accept: application/vnd.github.v3+json
      Content-Type: application/json
      User-Agent: Home Assistant REST sensor
