- alias: "Notifica di login fallito"
  initial_state: 'on'
  trigger:
   - platform: state
     entity_id: persistent_notification.http_login
  condition:
  - condition: template
    value_template: "{{ trigger.to_state.state != 'None' }}"
  action:
  - service: notify.telegram
    data_template:
      title: "{{ states.persistent_notification.http_login.attributes.message }}"
      message: 'url: https://whatismyipaddress.com/ip/{{ states.persistent_notification.http_login.attributes.message.split ("from ") [1]}}'
  - service: persistent_notification.dismiss
    data:
      notification_id: 'http_login'