automation:

################################################################################
#                                                                              #
############################### AVVIO HA ALEXA #################################
#                       installare Alexa-MediaPlayer (HACS)                    #
################################################################################

  - alias: 'Avvio HA Alexa'
#    initial_state: true
    trigger:
      - platform: homeassistant 
        event: start
    condition:
      - condition: time
        after: '09:00:00'
        before: '22:00:00'
        weekday:
          - mon
          - tue
          - wed
          - thu
          - fri
          - sat
          - sun
    action:          
      - service: media_player.volume_set
        entity_id: media_player.#<nome echo>
        data:
          volume_level: 0.5
      - delay: '00:00:05'
      - service: notify.alexa_media
        data_template:
          data:
            type: announce
          target: media_player.#<nome echo>
          message: >
            {{ [
            "Home Assistant è operativo, oggi è {{ states('sensor.giorno_della_settimana') }} e sono le ore {{ states('sensor.time') }}",
            "Oggi è un nuovo giorno, Home Assistant è operativo", 
            "Buongiorno, buonasera, Home Assistant è pronto",
            "Home Assistant è operativo, cosa vuoi fare oggi",
            "Signori e Signore, Ladies and Gentlemen, Home Assistant è operativo"
            ] | random }}
      - delay: '00:00:15' 
      - service: media_player.volume_set
        entity_id: media_player.#<nome echo>
        data:
          volume_level: 0.1

################################################################################
#                                                                              #
################################ AVVISO RIFIUTO ################################
#                                                                              #
################################################################################

  - alias: 'Alexa Raccolta'
    trigger:
      - platform: time
        at: '19:30:00'
    condition:
    action:
      - service: notify.alexa_media
        data_template:
          data:
            type: announce
          target: media_player.#<nome echo>
          message: "oggi c'è da buttare {{ states('sensor.spazzatura') }}"
