automation:

################################################################################
#                                                                              #
#################################  BACKUP FULL #################################
#                                                                              #
################################################################################

  - alias: 'Backup Full Automatico'
    trigger:
      - platform: time 
        at: '10:00:00'
    condition:
      - condition: time
        weekday:
          - mon
    action:
      - service: hassio.snapshot_full
        data_template:
          name: Automated Full Backup {{ now().strftime("%d-%m-%Y") }}

################################################################################
#                                                                              #
############################# BACKUP PARZIALE ##################################
#                                                                              #
################################################################################

  - alias: 'Backup Partial Automatico'
    trigger:
      - platform: time
        at: '11:00:00'
    condition:
      - condition: time
        weekday:
          - mon
          - thu
          - sat
    action:
      - service: hassio.snapshot_partial
        data_template:
          name: Automated Backup {{ now().strftime("%d-%m-%Y") }}

################################################################################
#            in folders selezionate le cartelle che vi interessano,            #                                                                              #
#                  homeassistant è la vostra cartella /config                  #
################################################################################

          folders:
            - homeassistant 

################################################################################
#                      in addons inserire id - nome addon,                     #
#                          ad esempio a0d7b954_nodered,                        #
#           l'id cambia se hass.io addon o la comunity o se esterno            #
################################################################################

          addons: 
            - a0d7b954_nodered          

#          repositories: 
#            - https://github.com/hassio-addons/repository
#            - https://github.com/esphome/hassio   

################################################################################
#                                                                              #
################################# STOP BACKUP ##################################
#                                                                              #
################################################################################ 

  - alias: 'Stop Backup'
    trigger:
      - platform: numeric_state
        above: '85'
        below: '90'
        entity_id: sensor.disk_use_percent
    action:
      - service: notify.telegram_giancarlo
        data:
          message: Spazio libero in esaurimento!
      - service: automation.turn_off
        data:
          entity_id: automation.backup_full_automatico, automation.backup_partial_automatico
      - service: notify.telegram_giancarlo
        data:
          message: Backup Automatico disattivato
