automation:
################################################################################
#                              BACKUP FULL DROPBOX                             #
#                          scaricare ed attivare in addon                      #
#                  https://github.com/danielwelch/hassio-dropbox-sync          #
################################################################################

  - alias: 'Backup Full Dropbox'
    trigger:
      - platform: time
        at: '11:00:00'  #scegliere l'orario in base al backup full + 1 ora
    condition:
      - condition: time
        weekday:
          - mon
    action:
      - service: hassio.addon_stdin
        data:
          addon: 7be23ff5_dropbox_sync
          input:
            command: upload

################################################################################
#                            BACKUP PARZIALE DROPBOX                           #
#                        scaricare ed attivare in addon                        #
#              https://github.com/danielwelch/hassio-dropbox-sync              #
################################################################################

  - alias: 'Backup Partial Dropbox'
    trigger:
      - platform: time
        at: '12:00:00'  #scegliere l'orario in base al backup parziale + 1 ora
    condition:
      - condition: time
        weekday:
          - mon
          - thu
          - sat
    action:
      - service: hassio.addon_stdin
        data:
          addon: 7be23ff5_dropbox_sync
          input:
            command: upload
