automation:

################################################################################
#                                                                              #
################################# RIAVVIO HA ###################################
#                                                                              #
################################################################################

  - alias: 'Riavvio HA'
#    initial_state: true
    trigger:
      - platform: time
        at: 07:00:00
    condition:
      - condition: time
        weekday:
          - mon
          - tue
          - wed
          - thu
          - fri
          - sat
          - sun
    action:
      - service: homeassistant.restart
      
