automation:

################################################################################
#                                                                              #
################################# CAMBIO TEMA ##################################
#                                                                              #
################################################################################

  - alias: 'Tema Diurno'
    trigger:
      - platform: homeassistant
        event: start
      - platform: state
        entity_id: binary_sensor.sun
        to: 'on'
    condition:
      - condition: state
        entity_id: binary_sensor.sun
        state:  'on'
    action:
      - service: frontend.set_theme
        data:
          name: 'default'
          
  - alias: 'Tema Notturno'
    trigger:
      - platform: homeassistant
        event: start
      - platform: state
        entity_id: binary_sensor.sun
        to: 'off'
    condition:
      - condition: state
        entity_id: binary_sensor.sun
        state:  'off'
    action:
      - service: frontend.set_theme
        data:
          name: 'ios-dark-mode'
