sensor:
  - platform: moon
  - platform: template
    sensors:
      fasi_lunari:
        friendly_name_template: "Luna"
        entity_id: sensor.moon, sensor.fasi_lunari
        value_template: "{{ {
            'new_moon' : 'Luna Nuova [congiunzione o fase di novilunio]',
            'waxing_crescent' : 'Luna Crescente',
            'first_quarter' : 'Primo Quarto',
            'waxing_gibbous' : 'Gibbosa Crescente',
            'full_moon' : 'Luna Piena [opposizione o fase di plenilunio]',
            'waning_gibbous' : 'Gibbosa Calante',
            'last_quarter' : 'Ultimo Quarto',
            'waning_crescent' : 'Luna Calante'
            } [states('sensor.moon')] }}"

        entity_picture_template: >
          {% set state = states('sensor.fasi_lunari').title().split(" [")[0].replace(' ','-') | lower %}
          {{ '/local/icons/fasi_lunari/{}.png'.format(state) }}

# 1 Luna nuova (o congiunzione o fase di novilunio)
# 2 Luna crescente
# 3 Primo quarto
# 4 Gibbosa crescente
# 5 Luna piena (o opposizione o fase di plenilunio)
# 6 Gibbosa calante
# 7 Ultimo quarto
# 8 Luna calante
# https://www.home-assistant.io/components/sensor.moon/
