#################################################################################
#                                                                               #
#                                      PIHOLE                                   #
#                                                                               #
#################################################################################

pi_hole:

  host: #mettere ip pihole se esterno ad hassio o localhost:4865 se addon
  location: admin
  ssl: false
  verify_ssl: true
  api_key: # lo trovate in pihole sotto settings/api-web interface

#################################################################################
#                                                                               #
#                                     TIMER                                     #
#                                                                               #
#################################################################################

input_select:

  pihole_time:
    name: Disable Time (minutes)
    options:
      - Select Time
      - 00:01
      - 00:05
      - 00:15
      - 00:30
      - 00:45
      - 00:60
    initial: Select Time
    
#################################################################################
#                                                                               #
#                                    SCRIPT                                     #
#                                                                               #
#################################################################################

script:

  'pihole_disable_timer_script':
    alias: Pihole disable timer
    sequence:
    - data_template:
        duration: '{{states.input_select.pihole_time.state}}'
      service: pi_hole.disable
      
#################################################################################
#                                                                               #
#                                     SENSORI                                   #
#                                                                               #
#################################################################################
  
sensor:

  - platform: rest
    name: pi hole status
    resource: http://IP-PIHOLE/admin/api.php?status
    value_template: '{{ value_json.status}}'

  - platform: rest
    name: pi hole version
    resource: http://IP-PIHOLE/admin/api.php?version
    value_template: '{{ value_json.versions}}'
    json_attributes:
      - core_current
      - core_latest
      - web_current
      - web_latest
      - FTL_current
      - FTL_latest

  - platform: template
    sensors:
    
      pihole_check:
        friendly_name: PiHole Check
        value_template: >-
          {% set core_current = states.sensor.pihole_version.attributes["core_current"] %}
          {% set core_latest = states.sensor.pihole_version.attributes["core_latest"] %}
          {% set web_current = states.sensor.pihole_version.attributes["web_current"] %}
          {% set web_latest = states.sensor.pihole_version.attributes["web_latest"] %}
          {% set ftl_current = states.sensor.pihole_version.attributes["FTL_current"] %}
          {% set ftl_latest = states.sensor.pihole_version.attributes["FTL_latest"] %}
          {% if core_current != core_latest %} update 
          {% elif web_current != web_latest %} update
          {% elif ftl_current != ftl_latest %} update
          {% else %} latest update
          {% endif %}
        icon_template: >-
          {% if is_state("sensor.pihole_check", "latest update") %} 
            mdi:checkbox-marked
          {% else %}
            mdi:cloud-download
          {% endif %}



binary_sensor:
  - platform: template
    sensors:
      pihole:
        friendly_name: "stato pihole"
        value_template: "{{ is_state('sensor.pi_hole_status','enabled') }}"
    
#################################################################################
#                                                                               #
#                               STRINGA PER LOVELACE                            #
#                                                                               #
#################################################################################

Da HACS scaricate le seguenti card:

button-card
bar-card
fold-entity-row
  
#per creare la card premere su + e selezionare manual card, copiare codice    
entities:
  - binary_sensor.pve_pihole_running
  - sensor.pihole_check
  - entities:
      - entity: binary_sensor.pihole_enable
        hold_action:
          action: call-service
          service: pi_hole.enable
        icon: 'mdi:pi-hole'
        name: PiHole Disabler Timer
        size: 30px
        state:
          - color: red
            value: 'off'
          - color: green
            value: 'on'
        style:
          - font-size: 8px
        tap_action:
          action: call-service
          service: script.pihole_timer_disabler
        type: 'custom:button-card'
      - entity: input_select.pihole_timer
      - color: red
        entity: sensor.pi_hole_ads_blocked_today
        title: PiHole ADS Blocked Today
        title_position: inside
        type: 'custom:bar-card'
      - color: blue
        entity: sensor.pi_hole_dns_queries_cached
        title: PiHole DNS Queries Cached
        title_position: inside
        type: 'custom:bar-card'
      - color: cornflowerblue
        entity: sensor.pi_hole_dns_queries_forwarded
        title: PiHole DNS Queries Forwarded
        title_position: inside
        type: 'custom:bar-card'
      - color: salmon
        entity: sensor.pi_hole_dns_queries_today
        title: PiHole DNS Queries Today
        title_position: inside
        type: 'custom:bar-card'
      - color: green
        entity: sensor.pi_hole_dns_unique_domains
        title: PiHole DNS Unique Domains
        title_position: inside
        type: 'custom:bar-card'
      - color: purple
        entity: sensor.pi_hole_domains_blocked
        title: PiHole Domains Blocked
        title_position: inside
        type: 'custom:bar-card'
      - entity: sensor.pi_hole_dns_unique_clients
      - entity: sensor.pi_hole_seen_clients
    head: binary_sensor.pihole_enable
    type: 'custom:fold-entity-row'
type: entities
