#################################################################################
#                                                                               #
#                                      PIHOLE                                   #
#                                                                               #
#################################################################################

pi_hole:

  host: #mettere ip pihole se esterno ad hassio o localhost:4865 se addon
  location: admin
  ssl: false
  verify_ssl: true
  api_key: # lo trovate in pihole sotto settings/api-web interface

#################################################################################
#                                                                               #
#                                     TIMER                                     #
#                                                                               #
#################################################################################

input_select:

  pihole_time:
    name: Disable Time (minutes)
    options:
      - Select Time
      - 00:01
      - 00:05
      - 00:15
      - 00:30
      - 00:45
      - 00:60
    initial: Select Time
    
#################################################################################
#                                                                               #
#                                    SCRIPT                                     #
#               SE VI PIACE IL COMANDO ESEGUI ALTRIMENTI AUTOMATION             #
#################################################################################

script:

  'pihole_enable':
    alias: Pihole enable
    sequence:
    - service: pi_hole.enable
  
  'pihole_disable_timer':
    alias: Pihole disable timer
    sequence:
    - data_template:
        duration: '{{states.input_select.pihole_time.state}}'
      service: pi_hole.disable

#################################################################################
#                                                                               #
#                                      AUTOMATION                               #
#                             SE VI PIACCIONO LE AUTOMAZIONI                    #
#################################################################################

automation:

  - alias: 'pihole enable'
    description: pihole enabler
    trigger:
    condition:
    action:
    - service: pi_hole.enable
  
  - alias: 'pihole disable timer'
    description: pihole disable timer
    trigger: 
    condition: 
    action:
    - data_template:
        duration: '{{states.input_select.pihole_time.state}}'
      service: pi_hole.disable

#################################################################################
#                                                                               #
#                                     SENSORI                                   #
#                                                                               #
#################################################################################
  
sensor:

  - platform: command_line
    name: PiHole Status
    command: "curl -X GET 'http://IP-PIHOLE/admin/api.php?status'"  
    value_template: '{{ value_json.status }}'
    scan_interval: 10  

  - platform: command_line
    command: "curl -X GET 'http://IP-PIHOLE/admin/api.php?versions'"
    name: PiHole Core
    value_template: >-
                Core Update: {{ value_json.core_update}} 
                Current: {{ value_json.core_current}}  
                Latest: {{ value_json.core_latest}}
                Web Update : {{ value_json.web_update}} 
                Current: {{ value_json.web_current}}   
                Latest: {{ value_json.web_latest}}
                FTL Update : {{ value_json.FTL_update}} 
                Current: {{ value_json.FTL_current}} 
                Latest: {{ value_json.FTL_latest}}
        
sensor:

  - platform: command_line
    name: pihole status
    command: !secret pihole_status_curl
    value_template: '{{ value_json.status }}'
    scan_interval: 10

  - platform: rest
    name: pi hole status
    resource: !secret pihole_status
    value_template: '{{ value_json.status}}'

  - platform: rest
    name: pi hole version
    resource: !secret pihole_version
    value_template: '{{ value_json.versions}}'
    json_attributes:
      - core_update
      - core_current
      - core_latest
      - web_update
      - web_current
      - web_latest
      - FTL_update
      - FTL_current
      - FTL_latest

  - platform: template
    sensors:
      pi_hole_core:
        value_template: "{%- if states.sensor.pi_hole_version.attributes.core_current == states.sensor.pi_hole_version.attributes.core_latest -%} {{states.sensor.pi_hole_version.attributes.core_current}} {% else %} {{states.sensor.pi_hole_version.attributes.core_latest}} Available {% endif%}"
        icon_template: >-
          {% if states.sensor.pi_hole_version.attributes.core_current == states.sensor.pi_hole_version.attributes.core_latest %}
            mdi:checkbox-marked
          {% else %}
            mdi:checkbox-blank-outline
          {% endif %}
        
  - platform: template
    sensors:
      pi_hole_web:
        value_template: "{%- if states.sensor.pi_hole_version.attributes.web_current == states.sensor.pi_hole_version.attributes.web_latest -%} {{states.sensor.pi_hole_version.attributes.core_current}} {% else %} {{states.sensor.pi_hole_version.attributes.core_latest}} Available {% endif%}"
        icon_template: >-
          {% if states.sensor.pi_hole_version.attributes.web_current == states.sensor.pi_hole_version.attributes.web_latest %}
            mdi:checkbox-marked
          {% else %}
            mdi:checkbox-blank-outline
          {% endif %}
        
  - platform: template
    sensors:
      pi_hole_ftl:
        value_template: "{%- if states.sensor.pi_hole_version.attributes.ftl_current == states.sensor.pi_hole_version.attributes.ftl_latest -%} {{states.sensor.pi_hole_version.attributes.core_current}} {% else %} {{states.sensor.pi_hole_version.attributes.core_latest}} Available {% endif%}"
        icon_template: >-
          {% if states.sensor.pi_hole_version.attributes.ftl_current == states.sensor.pi_hole_version.attributes.ftl_latest %}
            mdi:checkbox-marked
          {% else %}
            mdi:checkbox-blank-outline
          {% endif %}          
    

#################################################################################
#                                                                               #
#                               STRINGA PER LOVELACE                            #
#                                                                               #
#################################################################################
#aggiungere in editor grezzo di lovelace come prima stringa
#(valido solo se scaricato da HACS)
resources:
  - type: module
    url: /community_plugin/lovelace-fold-entity-row/fold-entity-row.js
    
#per creare la card premere su + e selezionare manual card, copiare codice    
entities:
  - sensor.pihole_status
  - input_select.pihole_time
  - automation.pihole_disable_timer
  - automation.pihole_enable
  - entities:
      - entity: sensor.pi_hole_ads_percentage_blocked_today
      - entity: sensor.pi_hole_ads_blocked_today
      - entity: sensor.pi_hole_dns_queries_cached
      - entity: sensor.pi_hole_dns_queries_forwarded
      - entity: sensor.pi_hole_dns_queries_today
      - entity: sensor.pi_hole_dns_unique_clients
      - entity: sensor.pi_hole_dns_unique_domains
      - entity: sensor.pi_hole_domains_blocked
      - entity: sensor.pi_hole_seen_clients
      - entity: sensor.pihole_core
    head: binary_sensor.pve_pihole_running
    type: 'custom:fold-entity-row'
type: entities
