sensor:

  - platform: template
    sensors:
    
      # spazzatura:
      #   friendly_name: Ritiro
      #   entity_id: sensor.date
      #   icon_template: mdi:delete-empty
      #   value_template: >         
      #     {% if now().strftime('%A') == 'Monday' %} Umido
      #     {% elif now().strftime('%A') == 'Tuesday' %} Non riciclabile
      #     {% elif now().strftime('%A') == 'Wednesday'%} Carta (Umido da Giugno a Ottobre)
      #     {% elif now().strftime('%A') == 'Thursday'%} Vetro
      #     {% elif now().strftime('%A') == 'Saturday' %} Nessun ritiro
      #     {% elif now().strftime('%A') == 'Sunday'%} Plastica
      #     {% elif now().strftime('%A') == 'Friday' %} Umido
      #     {% endif %}

      spazzatura:
        friendly_name: "Ritiro"
        entity_id: sensor.date
        value_template: >
          {{ {
          'Monday': 'Umido', 
          'Tuesday': 'Non riciclabile',
          'Wednesday': 'Carta (Umido da Giugno a Ottobre)', 
          'Thursday': 'Vetro',
          'Friday': 'Umido',
          'Saturday': 'Nessun ritiro',
          'Sunday': 'Plastica'
          } [ now().strftime('%A') ] }}

      spazzatura_3:
        friendly_name: "Ritiro 3"
        entity_id: sensor.date
        value_template: >
          {% set inverno = ["Umido", "Non riciclabile", "Carta", "Vetro", "Umido", "Nessun ritiro", "Plastica"] %} 
          {% set estate =  ["Umido", "Non riciclabile", "Carta e Umido", "Vetro", "Umido", "Nessun ritiro", "Plastica"] %} 
          {% set ritiro_inverno = inverno[now().weekday()] %}
          {% set ritiro_estate = estate[now().weekday()] %}
          {% if now().month in [6,7,8,9,10]  %}
            {{ ritiro_estate }}
          {% else %}
            {{ritiro_inverno}}
          {% endif %}

automation:

  - alias: 'Tipo Raccolta'
    trigger:
      - at: '19:30:00'
        platform: time
    action:
      - service: notify.telegram_giancarlo
        data_template:
          message: '{% if now().strftime(''%A'') == ''Monday'' %} Umido
                    {% elif now().strftime(''%A'') == ''Tuesday'' %} Non riciclabile  
                    {% elif now().strftime(''%A'') == ''Wednesday''%} Carta (Umido da Giugno a Ottobre)  
                    {% elif now().strftime(''%A'') == ''Thursday''%} Vetro  
                    {% elif now().strftime(''%A'') == ''Friday'' %} Umido 
                    {% elif now().strftime(''%A'') == ''Sunday''%} Plastica  
                    {% endif %}'

  - alias: 'Notifica Raccolta'
    trigger:
      - at: '19:30:00'
        platform: time
    action:
      - service: notify.telegram_giancarlo
        data_template:
          message: "{{ states('sensor.spazzatura') }}"
      - service: input_select.select_option
        entity_id: input_select.spazzatura
        data_template:
          option: "{{ states('sensor.spazzatura') }}"

  - alias: 'Alexa Raccolta'
    trigger:
      - platform: time
        at: '19:30:00'
    condition:
    action:
      - service: notify.alexa_media
        data_template:
          data:
            type: announce
          target: media_player.echo_plus_di_giancarlo
          message: "oggi c'è da buttare {{ states('sensor.spazzatura') }}"

input_select:
  spazzatura:
    name: tipo
    options:
      - Plastica
      - Umido
      - Carta (Umido da Giugno a Ottobre)
      - Non riciclabile
      - Vetro
      - Nessun ritiro
    initial: Nessun ritiro
    icon: mdi:delete-empty
