automation:
  - alias: 'Tipo Raccolta'
    trigger:
      - at: '19:30:00'
        platform: time
    action:
      - service: notify.telegram
        data_template:
          message: '{% if now().strftime(''%A'') == ''Monday'' %} Umido
                    {% elif now().strftime(''%A'') == ''Tuesday'' %} Non riciclabile  
                    {% elif now().strftime(''%A'') == ''Wednesday''%} Carta (Umido da Giugno a Ottobre)  
                    {% elif now().strftime(''%A'') == ''Thursday''%} Vetro  
                    {% elif now().strftime(''%A'') == ''Friday'' %} Umido 
                    {% elif now().strftime(''%A'') == ''Sunday''%} Plastica  
                    {% endif %}'

sensor:
  - platform: template
    sensors:
      spazzatura:
        friendly_name: Ritiro
        entity_id: sensor.date
        icon_template: mdi:delete-empty
        value_template: >-
           {% if now().strftime('%A') == 'Monday' %} Umido
           {% elif now().strftime('%A') == 'Tuesday' %} Non riciclabile
           {% elif now().strftime('%A') == 'Wednesday'%} Carta (Umido da Giugno a Ottobre)
           {% elif now().strftime('%A') == 'Thursday'%} Vetro
           {% elif now().strftime('%A') == 'Friday' %} Umido
           {% elif now().strftime('%A') == 'Saturday' %} Nessun ritiro
           {% elif now().strftime('%A') == 'Sunday'%} Plastica
           {% endif %}
